name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    name: Build and Test on ${{ matrix.os }}
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build - Release
        run: dotnet build -c Release src/Interprocess.sln

      - name: Test - Debug
        run: dotnet test src/Interprocess.sln