name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test on Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: dotnet build --configuration Release src/Interprocess.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal src/Interprocess.sln

    runs-on: windows-latest
    name: Build and Test on Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: dotnet build --configuration Release src/Interprocess.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal src/Interprocess.sln