name: Integration for PRs
on:
  pull_request:
  workflow_dispatch:
jobs:
  build_and_test:
    strategy:
      matrix:
        config:
        - { os: ubuntu-latest, name: 'linux'}
        - { os: macos-latest, name: 'macos'}
        - { os: windows-latest, name: 'windows'}
    runs-on: ${{ matrix.config.os }}
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: "3.1.x"
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: "5.0.x"
      - name: Build
        run: dotnet build src/Interprocess.sln -c Release
      - name: Test
        run: dotnet test src/Interprocess.sln --no-build -c Release --logger GitHubActions
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Interprocess-${{ matrix.config.name }}
          path: |
            src/artifacts/*.nupkg
          if-no-files-found: error
      - name: Report Coverage to PR
        uses: StirlingLabs/PROutputAction@v1.0.1
        with:
          sources: '.github/coverage/prefix,coverage/,.github/coverage/suffix'
          token: ${{github.token}}