name: publish

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test Pack and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: dotnet build --configuration Release src/Interprocess.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal src/Interprocess.sln
      - name: Push
        run: dotnet nuget push Interprocess.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nuget_org_api_key }}